config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :post_image
  belongs_to :users
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :user
  has_many :post_commtents, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end


  attachment :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_image, dependent: :destroy
  has_many :post_commtents, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.new(post_image_id: post_image.id)
    favorite.save
    redirect_to post_image_path(post_image)
  end
  
  def destroy
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.find_by(post_image_id: post_image.id)
    favorite.destroy
    redirect_to post_image_path(post_image)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    post_image = PostImage.find(params[:post_image_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_image_id = post_image.id
    comment.save
    redirect_to post_image_path(post_image)
  end
  
  def destroy
    PostComment.find_by(id: params[:id], post_image_id: params[:post_image_id]).destroy
    redirect_to post_image_path(params[:post_image_id])
  end
  
  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
  
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def index
    @post_images=PostImage.page(params[:page]).reverse_order
  end

  def show
    @post_image=PostImage.find(params[:id])
    @post_comment=PostComment.new
  end

  def new
    @post_image=PostImage.new
  end

  def create
    @post_image=PostImage.new(post_image_params)
    @post_image.user_id=current_user.id
    @post_image.save
    redirect_to post_images_path
  end

  def destroy
    @post_image=PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end


  private

  def post_image_params
    params.require(:post_image).permit(:shop_name, :caption, :image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user=User.find(params[:id])
    @post_images = @user.post_images.page(params[:page]).reverse_order
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(current_user)
  end

  private

  def user_params
    params.require(:user).permit(:name , :profile_image)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<h1>welcome to <strong>Meshittero</strong>!!</h1>
<h3>in <strong>Meshittero</strong></h3>

<p>SNS community that indiscriminately stimulates the appetite of sensible citizens.</p>

<%= link_to"Log in", new_user_session_path %>

<%= link_to"Sign Up",  new_user_registration_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshittero2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
      <li><%= link_to"ログアウト", destroy_user_session_path,method: :delete %></li>
      <li><%= link_to"投稿フォーム", new_post_image_path %></li>
      <li><%= link_to"マイページ", user_path(current_user) %></li>
      <% else %>
      <li><%= link_to"新規登録",  new_user_registration_path %></li>
      <li><%= link_to"ログイン", new_user_session_path %></li>
      <% end %>
    </header>

    <main>
    <%= yield %>
    </main>

  <footer>
    <p>善良な市民同士で無差別に食欲を煽るSNS</p>
  </footer>
  </body>
</html>

app/views/post_images/index.html.erb
<%= @post_images.each do |post_image| %>

<%= link_to post_image_path(post_image.id) do %>
<%= attachment_image_tag post_image, :image %>
<% end %>

<p>ユーザー画像</p>

<%= link_to post_image_path(post_image.idr) do %>
<%= post_image.shop_name %>
<% end %>

<%= post_image.caption %>

<p>By <%= post_image.user.name %></p>
<p><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id) %></p>

<% end %>

app/views/post_images/new.html.erb
<h1>画像投稿フォーム</h1>

<%= form_with model: @post_image, local:true do |f| %>

<%= f.attachment_field :image %>

<p>店名：<%= f.text_field :shop_name %></p>

<p>紹介：<%= f.text_area :caption %></p>

<%= f.submit'投稿' %>

<% end %>

app/views/post_images/show.html.erb
<%= attachment_image_tag @post_image, :image %>

<p>ユーザー画像</p>

<%= link_to post_image_path do %>
<%= @post_image.shop_name %>
<% end %>

<%= @post_image.caption %>

<p>By <%= @post_image.user.name %></p>

<% if @post_image.user == current_user %>
<%= link_to"削除", post_image_path, method: :delete %>
<% end %>

<div class="comments">
<p>コメント件数：<%= @post_image.post_comments.count %></p>
<% @post_image.post_comments.each do |post_comment| %>
  <p><%= image_tag('sample-author1.jpg') %></p>
  <%= post_comment.user.name %>
  <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
  
<% end %>
</div>
<div class="new-comment">
<%= form_with(model:[@post_image, @post_comment], local: true) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
  <%= f.submit "送信する" %>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>プロフィール編集</h1>

<%= form_with model:@user, local:true do |f| %>

<%= f.text_field :name %>

<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>

<%= f.attachment_field :profile_image %>

<%= f.submit'変更を保存' %>

<% end %>

app/views/users/show.html.erb
<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>

<%= @user.name %>

<% if user == current_user %>
<%= link_to"プロフィール編集", edit_user_path(@user) %>
<% end %>

<%= @post_images.each do |post_image| %>

<%= link_to post_image_path(post_image.id) do %>
<%= attachment_image_tag post_image, :image %>
<% end %>

<p>ユーザー画像</p>

<%= link_to post_image_path(post_image.idr) do %>
<%= post_image.shop_name %>
<% end %>

<%= post_image.caption %>

<p>By <%= post_image.user.name %></p>

<% end %>